package main

// 21. Каким образом реализован механизм исключений?

// Ответы:
// panic, defer, recovery

func main() {

}

